sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/lychee
    - secure: "YyifJnqmpJ3ze/GOYkGHycjfYZQgV9SgCFKmriUhaVPJd2wjtHg7ijveeLm1eiTOyprcrc/Mnx7Y/11Csqrvk8TluSwDQDxGKwoOPnLzBEA9wfV6Cfx3PIp28DUDtruveKVx66Vbvhu5ANMM7PqDqUSTt2lvhi/NHru5YugdtOJsl1/07U1jcs8TsMK4R5DkdNIyfbd8rgNps+hu6kwkX39qDefA2q9mosKNfFbXoUhOWUZo2u2t2jqY/ChdIuMtIHVgYrODs9f0Rxhoq+6e+0rYwA2j9CZ1f8mp280s2lVfkmTnmjdn4GHYH4FjknnAlpR6yT2lyWuvFaeWeiWuQx19p8jiFyHMvRxnlWbMDoJFZ3AeeHoyNL2vyTRespV5QoxQQAll3gTKSMGI0E+wi82QANAXZr4Hwkl3gqSkPEgwuIamD7TN2LWDh3A73uf/d0BYlLEiirY2ztSwBTDaAXWPCHVGQtGdBAHGFwdh+gp7F2qtqqLWhsf1p3sca35Zu2Dpp6Y6jd0OpJ3a+TmqbFafH1l15+BdrtuDO6/F/B5xSOEmPJqAIKmXOu478F/+9FrVRzdBm1jumTGlsKVWRr+C4p40A4EBiqliI7q8cKtD9yBmlwFHATFgcpkfOBDPkLUcOwvQVJef51NXyxbHBtkHUHfo4ecFHCtBpWmrqT0="
